version: "3.9"
services:
  devopstut:
    image: devopstut
    container_name: devopstut
    ports:
      - "3000:3000"
    volumes:
      - devopstut:/app/data
    environment:
      - PUID=1001
      - PGID=999
    restart: unless-stopped
    networks:
      - npm_proxy
networks:
  npm_proxy:
    external: true